### PR TITLE
Fix sort order of projects to be alphabetical

### PR DESCRIPTION
**Pull request by rikvdh**
For example in the ProjectController index Redmine seems to do this, probably a good way to make this consistent everywhere.

Greetings,

Rik

### CODE REVIEW

**Comment by yandod** [comment]
it make sense for me.
can you show link to redmine code does this as well?

**Comment by rikvdh** [comment]
I'm not quite into Ruby, I have a Redmine installation which seem to do ```SELECT `projects`.* FROM `projects`  WHERE `projects`.`status` = 1 AND (projects.status <> 9) ORDER BY lft``` but project-ordering isn't implemented (already) which makes this more like a temporary solution.

**Comment by yandod** [comment]
@rikvdh could you have a link to sourcecode of redmine? i can take a look with you.

**Comment by rikvdh** [comment]
https://www.redmine.org/issues/6836

**Pull request closed without merging**
